# Generated by Django 6.0.6 on 2026-07-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog_derivaccount_oauthtoken_referral'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False, help_text='Only enabled bots can be used by customers.')),
                ('demo_only', models.BooleanField(default=True, editable=False)),
                ('max_stake', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=25, max_digits=12)),
                ('max_trades_per_day', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols', models.JSONField(default=list)),
                ('strategy', models.CharField(choices=[('over_2', 'Over 2'), ('under_7', 'Under 7')], default='over_2', max_length=12)),
                ('tick_window', models.PositiveIntegerField(default=100)),
                ('digit_threshold', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('stake', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('stopping', 'Stopping'), ('error', 'Error')], default='stopped', max_length=12)),
                ('selected_symbol', models.CharField(blank=True, max_length=32)),
                ('waiting_for', models.CharField(blank=True, max_length=32)),
                ('active_contract_id', models.CharField(blank=True, max_length=64)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.derivaccount')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='trading.automationbot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('strategy', models.CharField(max_length=12)),
                ('trigger_digit', models.PositiveSmallIntegerField()),
                ('contract_id', models.CharField(max_length=64, unique=True)),
                ('contract_type', models.CharField(max_length=24)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='open', max_length=16)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.automationrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.UniqueConstraint(fields=('user', 'bot'), name='one_run_per_user_bot'),
        ),
    ]
