# Generated by Django 6.0.6 on 2026-07-23 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_automationbot_automationrun_automationtrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='max_daily_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional user limit; leave blank to run until stopped.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='max_trades_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Optional user limit; leave blank to run until stopped.', null=True),
        ),
        migrations.AlterField(
            model_name='automationbot',
            name='max_daily_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional administrator ceiling. Leave blank for no daily loss cap.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='automationbot',
            name='max_stake',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional administrator ceiling. Leave blank to let users choose their stake.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='automationbot',
            name='max_trades_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Optional administrator ceiling. Leave blank for no daily trade cap.', null=True),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='stake',
            field=models.DecimalField(decimal_places=2, default='0.35', max_digits=12, validators=[django.core.validators.MinValueValidator('0.35')]),
        ),
    ]
