# Generated by Django 6.0.6 on 2026-07-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_automationrun_max_daily_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='digit_thresholds',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
