server {
    listen 80;
    server_name bot.profiteraa.com;

    root /var/www/deriv/static-apps/bot/current;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
