from django.urls import path
from .views import (
    bot_builder,
    dashboard,
    deriv_login,
    deriv_login_page,
    deriv_logout,
    deriv_oauth_callback,
    deriv_register,
    deriv_register_page,
    home,
    trade_hub,
    app_session,
    reset_demo_balance,
)

urlpatterns = [
    path('', home, name="home"),
    path('dashboard/', dashboard, name="dashboard"),
    path('trade/', trade_hub, name="trade"),
    path('analytics/', dashboard, name="analytics"),
    path('account/', dashboard, name="account"),
    path('bot-dashboard/', dashboard, name="bot_dashboard"),
    path('automatic-dashboard/', dashboard, name="automatic_dashboard"),
    path('automatic-trade/', bot_builder, name="automatic_trade"),
    path('build-bot/', bot_builder, name="build_bot"),
    path('bot-builder/', bot_builder, name="bot_builder"),
    path('api/deriv/app-session/', app_session, name="app_session"),
    path('account/reset-demo-balance/', reset_demo_balance, name="reset_demo_balance"),
    path('login/', deriv_login_page, name="login"),
    path('register/', deriv_register_page, name="register"),
    path('auth/deriv/login/', deriv_login, name="deriv_login"),
    path('auth/deriv/register/', deriv_register, name="deriv_register"),
    path('auth/deriv/callback', deriv_oauth_callback, name="deriv_oauth_callback_no_slash"),
    path('auth/deriv/callback/', deriv_oauth_callback, name="deriv_oauth_callback"),
    path('auth/deriv/logout/', deriv_logout, name="deriv_logout"),
]
