# Generated by Django 6.0.6 on 2026-07-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('profit', 'Profit'), ('loss', 'Loss'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
